### ISSUE TITLE
Не удалось загрузить изображение

### ISSUE THREAD

**Issue by LavirtheWhiolet** [Destiner/Dense#1]
![upload](https://cloud.githubusercontent.com/assets/231566/15805711/11235d98-2b54-11e6-985b-7dede3ce2471.png)

**Comment by Destiner** [comment]
Вроде исправил, теперь должно работать.

**Comment by LavirtheWhiolet** [comment]
Еще онлайновый вариант обнови.

**Comment by Destiner** [comment]
Если ты о Github Pages, то оно уже должно работать.
